[program:iptv-store-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/iptv-store/artisan queue:work redis --queue=high,default,low --tries=3 --timeout=90 --sleep=1 --max-jobs=1000 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/iptv-store/storage/logs/worker.log
stopwaitsecs=120
